"use client"

import { useState, useRef } from "react"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { FileText, Download, Loader2, Lock } from "lucide-react"
import { motion } from "framer-motion"
import {
  Bar,
  BarChart,
  CartesianGrid,
  Legend,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from "recharts"

interface MemberBreakdown {
  name: string
  commits: number
  githubAdditions: number
  githubDeletions: number
  githubPct: number
  docsPct: number
  docsMinutes: number
  docsLinesAdded: number
  docsLinesRemoved: number
}

interface ReportData {
  group: {
    name: string
    projectName?: string
    description: string | null
    githubRepo: string | null
    createdAt: string
  }
  members: {
    name: string
    githubUsername: string | null
    role: string
    joinedAt: string
  }[]
  contributions: {
    name: string
    score: number
    commits: number
    additions: number
    deletions: number
  }[]
  memberBreakdown?: MemberBreakdown[]
  chart?: {
    githubVsDocs: {
      name: string
      githubPct: number
      docsPct: number
      commits: number
      docsMinutes: number
    }[]
  }
  commitStats: {
    total: number
    totalAdditions: number
    totalDeletions: number
  }
  docsStats?: {
    entries: number
    totalMinutes: number
  }
  aiAnalysis: string | null
  aiGrades?: {
    name: string
    suggestedGrade: string
    scoreOutOf100: number
    justification: string
  }[]
  generatedAt: string
}

interface ReportGeneratorProps {
  groupId: string
  groupName: string
  hasData: boolean
  canViewReports: boolean
}

export function ReportGenerator({
  groupId,
  groupName,
  hasData,
  canViewReports,
}: ReportGeneratorProps) {
  const [report, setReport] = useState<ReportData | null>(null)
  const [isLoading, setIsLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const reportRef = useRef<HTMLDivElement>(null)

  const generateReport = async () => {
    setIsLoading(true)
    setError(null)

    try {
      const response = await fetch("/api/report", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ groupId }),
      })

      const data = await response.json()

      if (!response.ok) {
        throw new Error(data.error || "Failed to generate report")
      }

      setReport(data.report)
    } catch (error) {
      setError(error instanceof Error ? error.message : "Failed to generate report")
    } finally {
      setIsLoading(false)
    }
  }

  const downloadReport = () => {
    if (!report) return

    const grades =
      report.aiGrades && report.aiGrades.length > 0
        ? report.aiGrades
            .map(
              (g) =>
                `- ${g.name}: ${g.suggestedGrade} (${g.scoreOutOf100}/100)\n  ${g.justification}`
            )
            .join("\n\n")
        : ""

    const breakdown =
      report.memberBreakdown && report.memberBreakdown.length > 0
        ? report.memberBreakdown
            .map(
              (m) =>
                `${m.name}
  GitHub: ${m.commits} commits, +${m.githubAdditions}/-${m.githubDeletions} lines (est. share ${m.githubPct}%)
  Docs/Slides (logged): ${m.docsMinutes} min, +${m.docsLinesAdded}/-${m.docsLinesRemoved} lines (est. share ${m.docsPct}%)`
            )
            .join("\n\n")
        : report.contributions
            .map(
              (c, i) =>
                `${i + 1}. ${c.name}: ${c.score}%\n   - Commits: ${c.commits}\n   - Lines: +${c.additions} / -${c.deletions}`
            )
            .join("\n\n")

    const content = `
COLAB CONTRIBUTION REPORT
=============================
Generated: ${new Date(report.generatedAt).toLocaleString()}

PROJECT: ${report.group.projectName || report.group.name}
GROUP: ${report.group.name}
${report.group.description ? `Description: ${report.group.description}` : ""}
${report.group.githubRepo ? `Repository: ${report.group.githubRepo}` : ""}

TEAM MEMBERS (${report.members.length})
------------------
${report.members.map((m) => `- ${m.name} (${m.role})${m.githubUsername ? ` @${m.githubUsername}` : ""}`).join("\n")}

CONTRIBUTION SUMMARY (GitHub)
-----------------------------
Total Commits: ${report.commitStats.total}
Total Lines Changed: +${report.commitStats.totalAdditions} / -${report.commitStats.totalDeletions}

${report.docsStats ? `GOOGLE DOCS / SLIDES (self-reported logs)
--------------------------------
Entries: ${report.docsStats.entries}
Total minutes logged: ${report.docsStats.totalMinutes}
` : ""}

PER-MEMBER BREAKDOWN
--------------------
${breakdown}

${report.aiAnalysis ? `
GEMINI OVERVIEW
---------------
${report.aiAnalysis}
` : ""}

${grades ? `
AI SUGGESTED GRADES (DISCUSSION ONLY)
-------------------------------------
${grades}
` : ""}

---
Report generated by CoLab (https://colab.app)
    `.trim()

    const blob = new Blob([content], { type: "text/plain" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `${groupName.replace(/\s+/g, "_")}_contribution_report.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  const chartRows =
    report?.chart?.githubVsDocs?.map((r) => ({
      name: r.name.length > 14 ? `${r.name.slice(0, 12)}…` : r.name,
      GitHub: r.githubPct,
      "Docs & Slides": r.docsPct,
      commits: r.commits,
      docsMinutes: r.docsMinutes,
    })) ?? []

  if (!canViewReports) {
    return (
      <motion.div
        initial={{ opacity: 0, y: 8 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.35 }}
      >
        <Card className="border-dashed border-primary/25 bg-muted/20">
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-base">
              <Lock className="h-5 w-5 text-muted-foreground" />
              Contribution reports
            </CardTitle>
            <CardDescription>
              Only the instructor who created this group can generate and download official reports.
            </CardDescription>
          </CardHeader>
        </Card>
      </motion.div>
    )
  }

  return (
    <motion.div
      initial={{ opacity: 0, y: 8 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.35 }}
    >
      <Card>
        <CardHeader>
          <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
            <div>
              <CardTitle className="flex items-center gap-2">
                <FileText className="h-5 w-5 text-primary" />
                Contribution report
              </CardTitle>
              <CardDescription>
                GitHub activity, logged Docs/Slides work, Gemini overview, and suggested grades
              </CardDescription>
            </div>
            <div className="flex flex-wrap gap-2">
              <Button
                onClick={generateReport}
                disabled={isLoading}
                variant={report ? "outline" : "default"}
                className="gap-2"
              >
                {isLoading ? (
                  <>
                    <Loader2 className="h-4 w-4 animate-spin" />
                    Generating...
                  </>
                ) : (
                  <>
                    <FileText className="h-4 w-4" />
                    {report ? "Regenerate" : "Generate report"}
                  </>
                )}
              </Button>
              {report && (
                <Button onClick={downloadReport} variant="gradient" className="gap-2">
                  <Download className="h-4 w-4" />
                  Download
                </Button>
              )}
            </div>
          </div>
        </CardHeader>
        <CardContent>
          {!hasData && (
            <p className="mb-4 rounded-lg border border-amber-500/30 bg-amber-500/10 px-3 py-2 text-sm text-amber-900 dark:text-amber-100">
              Limited data: connect GitHub and/or have students log Google Docs/Slides work for more accurate charts.
            </p>
          )}
          {error && <p className="text-destructive mb-4">{error}</p>}
          {report && (
            <div ref={reportRef} className="space-y-6">
              <div className="grid gap-4 sm:grid-cols-3">
                <div className="rounded-lg border border-border p-4">
                  <p className="text-sm text-muted-foreground">Total commits</p>
                  <p className="text-2xl font-bold text-foreground">{report.commitStats.total}</p>
                </div>
                <div className="rounded-lg border border-border p-4">
                  <p className="text-sm text-muted-foreground">Lines added</p>
                  <p className="text-2xl font-bold text-green-600">+{report.commitStats.totalAdditions}</p>
                </div>
                <div className="rounded-lg border border-border p-4">
                  <p className="text-sm text-muted-foreground">Lines removed</p>
                  <p className="text-2xl font-bold text-red-500">-{report.commitStats.totalDeletions}</p>
                </div>
              </div>

              {report.docsStats && (
                <div className="grid gap-4 sm:grid-cols-2">
                  <div className="rounded-lg border border-border p-4">
                    <p className="text-sm text-muted-foreground">Docs/Slides log entries</p>
                    <p className="text-2xl font-bold text-foreground">{report.docsStats.entries}</p>
                  </div>
                  <div className="rounded-lg border border-border p-4">
                    <p className="text-sm text-muted-foreground">Minutes logged (Docs/Slides)</p>
                    <p className="text-2xl font-bold text-foreground">{report.docsStats.totalMinutes}</p>
                  </div>
                </div>
              )}

              {chartRows.length > 0 && (
                <div>
                  <h4 className="mb-2 font-semibold text-foreground">
                    Estimated share: GitHub lines vs Docs/Slides activity
                  </h4>
                  <p className="mb-3 text-xs text-muted-foreground">
                    Percentages are separate domains (each sums to ~100% across the team). Docs/Slides uses self-reported minutes and line edits from the workspace.
                  </p>
                  <div className="h-80 w-full">
                    <ResponsiveContainer width="100%" height="100%">
                      <BarChart data={chartRows} margin={{ top: 8, right: 8, left: 0, bottom: 8 }}>
                        <CartesianGrid strokeDasharray="3 3" className="stroke-border/50" />
                        <XAxis dataKey="name" tick={{ fontSize: 11 }} interval={0} angle={-20} textAnchor="end" height={56} />
                        <YAxis tick={{ fontSize: 11 }} domain={[0, 100]} unit="%" />
                        <Tooltip
                          formatter={(value: number | string, name: string) => [`${value}%`, name]}
                        />
                        <Legend />
                        <Bar dataKey="GitHub" fill="oklch(0.55 0.2 285)" radius={[4, 4, 0, 0]} />
                        <Bar dataKey="Docs & Slides" fill="oklch(0.65 0.15 200)" radius={[4, 4, 0, 0]} />
                      </BarChart>
                    </ResponsiveContainer>
                  </div>
                </div>
              )}

              {report.memberBreakdown && report.memberBreakdown.length > 0 ? (
                <div>
                  <h4 className="mb-3 font-semibold text-foreground">Detailed breakdown</h4>
                  <div className="space-y-2">
                    {report.memberBreakdown.map((m, index) => (
                      <div
                        key={index}
                        className="flex flex-col gap-1 rounded-lg border border-border p-3 sm:flex-row sm:items-center sm:justify-between"
                      >
                        <div>
                          <p className="font-medium text-foreground">{m.name}</p>
                          <p className="text-sm text-muted-foreground">
                            GitHub: {m.commits} commits · +{m.githubAdditions} / −{m.githubDeletions} lines · est.{" "}
                            {m.githubPct}% of code churn
                          </p>
                          <p className="text-sm text-muted-foreground">
                            Docs/Slides: {m.docsMinutes} min · +{m.docsLinesAdded} / −{m.docsLinesRemoved} lines · est.{" "}
                            {m.docsPct}% of logged doc work
                          </p>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              ) : (
                <div>
                  <h4 className="mb-3 font-semibold text-foreground">Contribution breakdown (stored scores)</h4>
                  <div className="space-y-2">
                    {report.contributions.map((c, index) => (
                      <div
                        key={index}
                        className="flex items-center justify-between rounded-lg border border-border p-3"
                      >
                        <div>
                          <p className="font-medium text-foreground">{c.name}</p>
                          <p className="text-sm text-muted-foreground">
                            {c.commits} commits · +{c.additions} / −{c.deletions}
                          </p>
                        </div>
                        <div className="text-right">
                          <p className="text-2xl font-bold text-primary">{c.score}%</p>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {report.aiAnalysis && (
                <div>
                  <h4 className="mb-3 font-semibold text-foreground">Gemini overview</h4>
                  <div className="rounded-lg border border-border bg-muted/30 p-4">
                    {report.aiAnalysis.split("\n").map((paragraph, index) => (
                      <p key={index} className="mb-2 text-sm text-foreground last:mb-0">
                        {paragraph}
                      </p>
                    ))}
                  </div>
                </div>
              )}

              {report.aiGrades && report.aiGrades.length > 0 && (
                <div>
                  <h4 className="mb-3 font-semibold text-foreground">AI suggested grades (discussion only)</h4>
                  <div className="space-y-3">
                    {report.aiGrades.map((g, i) => (
                      <div key={i} className="rounded-lg border border-border p-4">
                        <div className="flex flex-wrap items-baseline justify-between gap-2">
                          <p className="font-medium text-foreground">{g.name}</p>
                          <p className="text-lg font-semibold text-primary">
                            {g.suggestedGrade}{" "}
                            <span className="text-sm font-normal text-muted-foreground">({g.scoreOutOf100}/100)</span>
                          </p>
                        </div>
                        <p className="mt-2 text-sm text-muted-foreground">{g.justification}</p>
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>
          )}
        </CardContent>
      </Card>
    </motion.div>
  )
}
